### ISSUE TITLE
Doctrine profiling

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mattwood1/zf1#8]
```
Need to get Doctrine profiling

https://github.com/jokkedk/ZFDebug looks good - may have used it before.

Then hook in doctrine profiler.

```

Original issue reported on code.google.com by `matthew....@gmail.com` on 24 Sep 2013 at 11:50

**Comment by mattwood1** [comment]
I've added ZFDebug into the project in a new branch. It works but it's missing a few things.
1. Doctrine profiler - there is one written but it's not merged in and I can't get it to work.
2. XDebug profiler - could this be built into this tool bar.

Toolbar needs to be easily turned off / on.

**Comment by mattwood1** [comment]
Got XDebug working profiling the site. Closed.
